on: push
jobs:
  accept_commit:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - run: echo "build is NOT skipped"
  build:
    runs-on: ubuntu-latest
    needs: accept_commit
    steps:
    - run: echo "build job is executed"